[[msolve]]
arch = "aarch64"
git-tree-sha1 = "f2607ee41c7857d1883a5865889bda141edbad33"
os = "macos"

    [[msolve.download]]
    sha256 = "820ed13f3e645abd790fd4e927d711832f72dc7a419d8a511d2fd1a01d495d8f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.aarch64-apple-darwin.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "9ee20982c0161999e72dc9084cfc64dd92e19b4e"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "c9ab2bbf20a85196e142589cd1c4c7a9a0bada375a459f01a015a6faf506cd02"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.aarch64-linux-gnu.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "68717b5c8f14f9b3a007edfece6c353383a265e6"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "e5d13b24c8d245e92ec17e3d4b3179ecdae5700099630b13e6a8a2cdfdb25370"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.aarch64-linux-musl.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "fe0f85d4e94153de678c0e867c134b4432663c50"
os = "freebsd"

    [[msolve.download]]
    sha256 = "81994e4ced3010c3e1a9e46911dfe1c2ebf931f25912401a0647e4d0a93e0e3d"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.aarch64-unknown-freebsd.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "36cd81ba14ce121196c8f5293c70196853a16106"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "c27f6d9abe6c9a509d13e4a70ded2e8feab99e59fc1026c9d36eca2fae260984"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.armv6l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a5b046da08716b1f37007ed9fecf6511dd01e378"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "ba95b01c68f081e1736010fef5613ec5a44c33c492a1524d3738d86a047be68d"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.armv6l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1f52ffff43953c8393de7ef650568f7a9df63e16"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "0725aa870f8cb4af42865de8aa2468d4811edea3d637c0e52fb14f05d1ea9ea5"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.armv7l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "534602a4cb59a15c5acfdb438b0a0d061618609f"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "a30b5158dc1f3bb8f3dee62724c6461adb377e1666cb75f403f7c010b51d67a6"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.armv7l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "f76415de5ec68f69880c8bb9669093c13f46f384"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "1a7c9681ba44d1779a0e11d42ffa572372f736d7560600fb82b18b0ca3b6c5d7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.i686-linux-gnu.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "90dcc45bb9563b3818cef589705a6f3cb42f40db"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "1aca373f991a820c4fdab17bcc9a9129d636dd8ee2c68fe05fd1cfad1e10fd39"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.i686-linux-musl.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "ff5826b7b71951954ef50fcec2be85779873c8ca"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "79936c4247c6a9c75ece0e622c22abda47199b421e6cc162c77341ff5fbe2663"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.powerpc64le-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "a372e7a04aab166b5263959c0244b880ea5519ed"
os = "macos"

    [[msolve.download]]
    sha256 = "827b2cefb457e463e9c317a29fac0b19cdac1fff6797c5a987b24eee0ec322d0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.x86_64-apple-darwin.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "bb8402397f40428c87d4914b3b0d99227bab4d15"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "14a42e0245b7e51fbda8b7294a6d3580da1343795e9eba09d7eba6c6bb103edf"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.x86_64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "ded546ebe77647d7f31cab229d5f8ad9f4da7cae"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "2178f74d270866acffd8f6d0eaabf5465dce75746717ebe4a4186353c341cd85"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.x86_64-linux-musl.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "0043fdce85160b35e310003427f1507f9e5a6dc6"
os = "freebsd"

    [[msolve.download]]
    sha256 = "95cd9f9ee2b5f6670ac9c0820c9316c40fa13eb0925302b19596e6b9af24374c"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.800.1+0/msolve.v0.800.1.x86_64-unknown-freebsd.tar.gz"
