[[msolve]]
arch = "aarch64"
git-tree-sha1 = "abe24cbf4a62d644702e8568979d1976769b0e7e"
os = "macos"

    [[msolve.download]]
    sha256 = "c0df901a857ff70b55a7cd188b15f05a913ce605a94bd300352dccaa5a82c401"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.aarch64-apple-darwin.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "d9a5bd3dc2e791d83e6f5d563debc9ad20b1fbf6"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "e7683529322be96a2220db50d516eb6eccbea9a27cc8a22bf1687965e48f46a0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.aarch64-linux-gnu.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "fc44e82e23bdf21444dd189b21da1727c7433044"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "662b6e5c8eabbc6d4570956d795a38406547d1e4d43a8878e50e83eb24dc0ba0"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.aarch64-linux-musl.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "3a7e764ad9af8763b62bc452cb5eaebe7bc72a44"
os = "freebsd"

    [[msolve.download]]
    sha256 = "f9d772a4805bddcf813cde10d1d4d6c0d4bed33780f8798c2436a5875d9dc4ba"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.aarch64-unknown-freebsd.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "70bb5df3d0f61f305bd8664538c51b8dd86d0c05"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "cb28ef5fbdd8d0b2024801d64c68d97b2ff74e7dff3abe7c4b4e1168f72d2b01"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.armv6l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "41e738035276fbeee80d1dcdfbf527377bb1d502"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "a3dcca25c6d872d0c1d642870c6a69a7bba27719c97d398edbe5ccce68526b5d"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.armv6l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ec1bfab9e8ae2b9c2f8d1f37f12250c5d007864"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "da4705f27334030b0fe6d029e7a735e67d80a3413a2238ed3347173167414f7e"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.armv7l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f9782ac581ccb3c6893a075e7e35231f1cf44e23"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "57acd26d1b3fc26b7269367ec5f711c5e67001daf65fc9920d7af2bcb8a01527"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.armv7l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "0b00c88601d466508ced99be62958e38a08acf75"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "cb80a7b8405ecda05f9bf0872da0a570124f97eaa85c2742452d13c7e3636a19"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.i686-linux-gnu.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "77dc4228d3ecd25e8b879efdfb091410b5bbce83"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "3e8472b74de6873f40eca6ca19e39125a1becbbe09824628ce154f749e489395"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.i686-linux-musl.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "c9dcfb16806152b7b2c7a44c93f4d11ba458636d"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "6e5ec54c087e7b09db8dc92f7dae99acc1495ea41151d72a5dd8f8de6c6c44f1"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.powerpc64le-linux-gnu.tar.gz"
[[msolve]]
arch = "riscv64"
git-tree-sha1 = "b8b7a5009b7c565db23a772dd95fa618c81c9f0f"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "9999fd2b5d8c8ad25297706d93445a08c44e8effa66fa36c5ce2f9a30f1bf102"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.riscv64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "59dc95ece442b060864c98b5ece53e24c4ca087d"
os = "macos"

    [[msolve.download]]
    sha256 = "7141191a36e09b8a038183fc05bcfd80ee4582d65914ce72dc06709f9ecb6008"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.x86_64-apple-darwin.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "edce8cffa6c5f7c41bc7123c1237abb9309e18e2"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "e0ae24a85199e3b7e5943b32d1561f26e10693ca142c25a38137ceef7a7a6497"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.x86_64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "4668502de2c26ab17e60757bedfcf3468c626483"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "a5c4d54e9e9c24bcae5e9537f37b407bcdd528afc023e14f74dd23718f6e7a4b"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.x86_64-linux-musl.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "a38de406421e5646b0de8174fa42b766349b86af"
os = "freebsd"

    [[msolve.download]]
    sha256 = "4751e30c408272f046efa43d88a0748e0ed4f69e9d66c94f7d777f25010223aa"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.100+0/msolve.v0.900.100.x86_64-unknown-freebsd.tar.gz"
