[[msolve]]
arch = "aarch64"
git-tree-sha1 = "1a978f5ad5a06727e13dd8dd35b5a494b788f309"
os = "macos"

    [[msolve.download]]
    sha256 = "aef8d26cac68d94fec85a96b47cc0ee3439aeb3cd367527b1e277ba52a66b672"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.aarch64-apple-darwin.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "c9027b22e5e5803358016eda057cd99a6ea02d78"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "f745cfc77caa2f474366192926a691eea94770da0137eb3d47dffd029eb28788"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.aarch64-linux-gnu.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "0acd0fd563c8be00fbedfe4cbf86fa07a54ced6d"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "55af965639bda162d8197be32029e603eb63242a921e3ed300dcc91c67b3ea72"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.aarch64-linux-musl.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "5aee0f67e9ffa9fa0b13ef8451152cf19d68bfc6"
os = "freebsd"

    [[msolve.download]]
    sha256 = "3c44aad72dbd19f79532fa850b286bf018226e9c886d3eb4c39cae0c77a53e81"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.aarch64-unknown-freebsd.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9e8cc14f753be194a10897c0c7ad49bc150fbd0b"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "e67900a00b5dff8b7c7b7d93601336b9d08c416082e5c387663dad43c42c605d"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.armv6l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "93f4a4d53fd1c39a1670e31531e1962b85d123c7"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "84d7a14a4675711d69b97974c6576e72c7babad906e791cab77deada27a3484d"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.armv6l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1c9ad162d3b2235310e2d11966a0f63d626ccfa1"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "6f8eef45c664e7fd537818657b7b9abca55c91cc3ab4e431373d3988c4d9614b"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.armv7l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "17dc1217ea286661491bc4735c27b159aa8e79c1"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "5b69b3c75c99c9dc793167401f8b9dbcdd18f1e69af00a13962118978527d562"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.armv7l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "dac99348cd76da9652cee66a8113b90ec579a766"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "9a5c0ac8d8e685c4c7018a1d6b4471defe32ff573d9307172cc9a5894098d134"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.i686-linux-gnu.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "fd2cc47590ebc2d2c3f4330527c1cbedb83fb0cd"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "9b12d274a9c16f55b8e7e587e5f69bf19d18d285a054fd241364a509f3aa8826"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.i686-linux-musl.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "2092f9aa7154300d15fd7d43197f6cb8a316af2f"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "3001df91f397b48c1f4fddbac795d350896a506a13ee10ad155c2cd7383949e5"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.powerpc64le-linux-gnu.tar.gz"
[[msolve]]
arch = "riscv64"
git-tree-sha1 = "b0d6027e53e4688aba9b351e781248940c62070a"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "90c88b701489ed1b46d422605ea140585cc8f85b9bb989ee1e78320b94ed6d12"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.riscv64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "75a7c48101f9cf38ad1ad9696be2dff903300a03"
os = "macos"

    [[msolve.download]]
    sha256 = "c2b8d11322c41ffacdcae41001e70ff255a81decc604a096253f952b2c601bd7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.x86_64-apple-darwin.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "9df0dbe7d69d68a2ba0a438fb214d43fb897cd4f"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "a59c62bdded5e81d84cf9dfcb787430f806d4181abdf5ac44d29a8de7e4c3795"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.x86_64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "83c95c6f85adb991c28536ec0e303c7fa30bf98e"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "c27333fca27c23986f05a6c15ef78878f5f8f5e065de37960c1149ccdc70d064"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.x86_64-linux-musl.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "10181e3b85bc8491b8323d0cdb46914457504ef1"
os = "freebsd"

    [[msolve.download]]
    sha256 = "11b04d6163b4bd110b76503e059f9e42f6c4aaffd67587dc42f80d01e13b039b"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.1+0/msolve.v0.900.1.x86_64-unknown-freebsd.tar.gz"
