[[msolve]]
arch = "aarch64"
git-tree-sha1 = "baab516de13b55785b2824201647c9497fdaeea3"
os = "macos"

    [[msolve.download]]
    sha256 = "6951491730a9000dd612561c85e6e2ff584a1dcc7031a48a6325062ecb6de82e"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.aarch64-apple-darwin.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "8a5743983fa63ece7d2190de51041f4df4d307b0"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "483f72fd12d0a333584a0d2b68fccab2190b2832c20b650decaa9a6bd43aa193"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.aarch64-linux-gnu.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "93b3543b8d3b7990c82c77fd20e8e34dba19deee"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "ab1ac7eb8302aa2907e0bd9f42d44193992568fd9732687c030d3cdab55ec508"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.aarch64-linux-musl.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "42d35aae7a8f7189074b33e62fe3609a1d8fd4d5"
os = "freebsd"

    [[msolve.download]]
    sha256 = "d1447476f0fb15939f30861a92cfdf4e6fe18e7805bb8ca72fa46bc31cc08d28"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.aarch64-unknown-freebsd.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d028860f203c5f45e26126ba920278a6bd7ccf00"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "646bacc02c89bb27cb03f92cdc312d8d4ab0bad342c38795abe7a97bd01aede5"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.armv6l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "71d109e6b9841edf98b43a944ed3a9f092808e97"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "af261900260ea8715303e72cd364ae96041a651eca5639556992740aa24dc91e"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.armv6l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40c5bc20a328a0b6b7d8ee09943954ee57242a43"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "32b555b5e85b91f7d8404487ab7e688535fb1b74d0e2274f4a652b169b16c574"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.armv7l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0d14dba2853e704b4a0a9cb2a7c31bb157678814"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "54ff70e2fe6509302ab0ca20269b32fd37eecb0a44c91f2be520e7ba09ca97cd"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.armv7l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "a0e14b73b56e1579c53245d8197ea036ddf7b4cf"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "1cd62c8341fde40cad4d4adad905cbc67a52dec1bdf09e7099d814f4bda22f50"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.i686-linux-gnu.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "fd28c9054a13bb753c533f2ef1343e4dc5a01f43"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "b1d28459a1086d0211ea23b75adc0be754cf1ac0a5ecd578e900f17981e0b0ed"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.i686-linux-musl.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "b621fbe5c057dc7e98078a5535a4c8caa4b8bba9"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "4be3240cf88881ca8b122f9b8c43d40f53657be35fff149227befdf343fffdb9"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.powerpc64le-linux-gnu.tar.gz"
[[msolve]]
arch = "riscv64"
git-tree-sha1 = "8af5b573d9ea5a014bfe44b765df62011af74aef"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "9df2f5e1dabbea69002974f5d1fab17d59939f92e729e85ce42703926b9d905f"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.riscv64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "b4e613bf569a51843c2c5f61a13e9d29e0a51f09"
os = "macos"

    [[msolve.download]]
    sha256 = "42afd3b88ea45c7eb143525de65f90c4bcaf1b235645cc9a63a77fd1ea4f94e2"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.x86_64-apple-darwin.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "62cd27b1c514c168e6d33539343272496b53aac8"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "ac52290c6a47d0807d7fb1b68fb07f7642a2f4931631fa2089fe8844ae2e698c"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.x86_64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "2c36be72c7ae674ce3bd7b478be71c1fab7151fc"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "287e1fc0b85eb7e1e43ce375adb271de3d5bccf0e4a582330bb0c5fe8714e4e3"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.x86_64-linux-musl.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "d96d796d8684c1ec220e4358a3464cab8c546fce"
os = "freebsd"

    [[msolve.download]]
    sha256 = "da9561d934c92cfd8e19b8b32ba79d31c55f15b1c5dd0645b6c9287caa3335be"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.200+0/msolve.v0.900.200.x86_64-unknown-freebsd.tar.gz"
