[[msolve]]
arch = "aarch64"
git-tree-sha1 = "1a978f5ad5a06727e13dd8dd35b5a494b788f309"
os = "macos"

    [[msolve.download]]
    sha256 = "aef8d26cac68d94fec85a96b47cc0ee3439aeb3cd367527b1e277ba52a66b672"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.aarch64-apple-darwin.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "4982b14a077762ac7c3c9e52819b1e93ff7a8a97"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "d29b11cf91e898d5d3af13e01d1cb1400a410687c3dea5ccb3ff0cc79e4aa26e"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.aarch64-linux-gnu.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "00e961c7a8711fbdb1d3af5bbb576b5e0becaa22"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "dda1ff374146157023a65a1d4be9e4fb095ffb17730a26ad6a1c3954f0440408"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.aarch64-linux-musl.tar.gz"
[[msolve]]
arch = "aarch64"
git-tree-sha1 = "5aee0f67e9ffa9fa0b13ef8451152cf19d68bfc6"
os = "freebsd"

    [[msolve.download]]
    sha256 = "3c44aad72dbd19f79532fa850b286bf018226e9c886d3eb4c39cae0c77a53e81"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.aarch64-unknown-freebsd.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "657360c0d9d24a8b2992beba38d115af59fca8c7"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "66600ecaec44d71b9116eafe3eed0678f443cd4d469680a8cc9f11a7e6f1e164"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.armv6l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "47bd02dcbe8223321dc054361108ca34275f6943"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "62c091e4b263ccebf05ea52211e5cd12be0c1443e99582441641359b42eab5bb"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.armv6l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dce78fe9a49e0461c6fd086e8192fac54e9d8f1b"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "8b5fd1612db9fcc494d4fd9740cfda05eb6ff2aaa2836e3ae2d94d4321e2c373"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.armv7l-linux-gnueabihf.tar.gz"
[[msolve]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "133991ff442b38a9d2d120de8f463a4b479d1ec1"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "0824acfaea48a0857abe37a9f4fb4571b7179d8844c88c453b392e67bd6f1db3"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.armv7l-linux-musleabihf.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "62e4aaabf37119e5927465b9e2e02814690e825e"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "302c4820fff275378c513ee8a03ad056dbbac4b58e6217ed7e8afa7b9fd3bc79"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.i686-linux-gnu.tar.gz"
[[msolve]]
arch = "i686"
git-tree-sha1 = "926c6b6da71239820aa748c056bcd01aaf6f6ad9"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "b0924f32486c3bb0398c1a9d2167a8af36a47bf19c4e0e5df57183c48efced78"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.i686-linux-musl.tar.gz"
[[msolve]]
arch = "powerpc64le"
git-tree-sha1 = "fe385e9a2e22d54898691e429bf6c16aef0aed6b"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "081e5eed355cd2aff078f744724709a35686ef02d662c23c8a7885573f40aeeb"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.powerpc64le-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "75a7c48101f9cf38ad1ad9696be2dff903300a03"
os = "macos"

    [[msolve.download]]
    sha256 = "c2b8d11322c41ffacdcae41001e70ff255a81decc604a096253f952b2c601bd7"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.x86_64-apple-darwin.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "ade863708f7331764e114988a494dbc0917ccfe1"
libc = "glibc"
os = "linux"

    [[msolve.download]]
    sha256 = "e40638a164ac6291eb9349a5fe7946ed39586401ea0a1d6469e816da6fef218c"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.x86_64-linux-gnu.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "de45ea1c055339b95e0994964cb6cff488d5c0ce"
libc = "musl"
os = "linux"

    [[msolve.download]]
    sha256 = "66ae8042e0b50865f4724b14e7da9183cd3a32dd14f2aa51e074c19d4c6f1baa"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.x86_64-linux-musl.tar.gz"
[[msolve]]
arch = "x86_64"
git-tree-sha1 = "10181e3b85bc8491b8323d0cdb46914457504ef1"
os = "freebsd"

    [[msolve.download]]
    sha256 = "11b04d6163b4bd110b76503e059f9e42f6c4aaffd67587dc42f80d01e13b039b"
    url = "https://github.com/JuliaBinaryWrappers/msolve_jll.jl/releases/download/msolve-v0.900.0+0/msolve.v0.900.0.x86_64-unknown-freebsd.tar.gz"
